services:
  - type: web
    name: flask-neon-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DATABASE_URL
        sync: false  # Lo agregas en Render manualmente
